package day7_test

import (
	"fmt"
	"strings"

	"github.com/okulik/AoC2025/pkg/day7"
)

var testInput = `
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`

func ExampleTotalSplitCount() {
	count := day7.TotalSplitCount(strings.NewReader(testInput))
	fmt.Println(count)
	// Output:
	// 21
}

func ExampleTotalQuantumTimelinesCount() {
	count := day7.TotalQuantumTimelinesCount(strings.NewReader(testInput))
	fmt.Println(count)
	// Output:
	// 40
}
